# Generated by Django 4.2.20 on 2025-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentage',
            old_name='examen_points',
            new_name='exam_points',
        ),
        migrations.AddField(
            model_name='percentage',
            name='assistances_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de asistencias en el parcial. Ejemplo: 20.00'),
        ),
        migrations.AddField(
            model_name='percentage',
            name='exam_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje del examen en el parcial. Ejemplo: 20.00'),
        ),
        migrations.AddField(
            model_name='percentage',
            name='homework_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de tareas en el parcial. Ejemplo: 20.00'),
        ),
        migrations.AddField(
            model_name='percentage',
            name='projects_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de proyectos en el parcial. Ejemplo: 20.00'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='assistances_amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad de asistencias del parcial. Ejemplo: 50'),
        ),
    ]
