# Generated by Django 4.2.20 on 2025-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_examen_points_percentage_exam_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='projects_percentage',
        ),
        migrations.AddField(
            model_name='percentage',
            name='class_work_percentage',
            field=models.DecimalField(decimal_places=2, default=20, help_text=('Porcentaje de la calificación que se le asigna al trabajo en clase. Ejemplo: 20.00',), max_digits=5, verbose_name='Porcentaje trabajo en clase'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='assistances_amount',
            field=models.IntegerField(default=3, help_text='Número de asistencias que se le asignan al examen. Ejemplo: 3', verbose_name='Asistencias'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='assistances_percentage',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Porcentaje de la calificación que se le asigna a las asistencias. Ejemplo: 10.00', max_digits=5, verbose_name='Porcentaje asistencias'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='exam_percentage',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Porcentaje de la calificación que se le asigna al examen. Ejemplo: 50.00', max_digits=5, verbose_name='Porcentaje examen'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='exam_points',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Puntos / aciertos que se le asignan al examen. Ejemplo: 30.00', max_digits=5, verbose_name='Puntos examen'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='homework_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text=('Porcentaje de la calificación que se le asigna a las tareas. Ejemplo: 15.00',), max_digits=5, verbose_name='Porcentaje tareas'),
        ),
    ]
