# Generated by Django 4.2.20 on 2025-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_percentage_projects_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='class_work_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text=('Porcentaje de la calificación que se le asigna al trabajo en clase. Ejemplo: 20.00',), max_digits=5, verbose_name='Porcentaje trabajo en clase'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='homework_percentage',
            field=models.DecimalField(decimal_places=2, default=25, help_text=('Porcentaje de la calificación que se le asigna a las tareas. Ejemplo: 15.00',), max_digits=5, verbose_name='Porcentaje tareas'),
        ),
    ]
